# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fG8fzFFk0d-twlsM10X4hjDhjk65o6Ob
"""

import pandas as pd
import numpy as np
import seaborn as sns 

from matplotlib import pyplot as plt 
datos_dem = pd.read_excel('Archivo para codigo.xlsx', header=0)
datos_var = pd.read_excel('Temperatura y humedad.xlsx', header=0)
df = pd.DataFrame(data=datos_dem)
temp = pd.DataFrame(data=datos_var)
print(df)

df_to_array = df.values

Dem_P1 = df['P1'].values;
Dem_P3 = df['P3'].values;
Dem_P5 = df['P5'].values;
Dem_P7 = df['P7'].values;
Temp = temp['Min, Tempature °C'].values;
Humd = temp['Min Humidity %'].values;

print("Estadisticas descriptivas sobre la demanda energetica en boyaca")

datos_dem.shape
datos_dem.describe()
datos_dem.info()
sns.pairplot(datos_dem)

"""Graficas de la relacion de la demanda energetica y al temperatura

"""

plt.plot(Dem_P1, Temp, 'g^')
plt.xlabel('Demanda energetica')
plt.ylabel('Temperatura °C')
plt.title('Demanda energetica de la zona 1')
plt.show()

plt.plot(Dem_P3, Temp, 'g^')
plt.xlabel('Demanda energetica')
plt.ylabel('Temperatura °C')
plt.title('Demanda energetica de la zona 3')
plt.show()

plt.plot(Dem_P5, Temp, 'g^')
plt.xlabel('Demanda energetica')
plt.ylabel('Temperatura °C')
plt.title('Demanda energetica de la zona 5')
plt.show()

plt.plot(Dem_P7, Temp, 'g^')
plt.xlabel('Demanda energetica')
plt.ylabel('Temperatura °C')
plt.title('Demanda energetica de la zona 7')
plt.show()

"""Graficas de la relacion de la demanda energetica y la humedad"""

plt.plot(Dem_P1, Humd, 'g^')
plt.xlabel('Demanda energetica')
plt.ylabel('Humedad %')
plt.title('Demanda energetica de la zona 1')
plt.show()

plt.plot(Dem_P3, Humd, 'g^')
plt.xlabel('Demanda energetica')
plt.ylabel('Humedad %')
plt.title('Demanda energetica de la zona 3')
plt.show()

plt.plot(Dem_P5, Humd, 'g^')
plt.xlabel('Demanda energetica')
plt.ylabel('Humedad %')
plt.title('Demanda energetica de la zona 5')
plt.show()

plt.plot(Dem_P7, Humd, 'g^')
plt.xlabel('Demanda energetica')
plt.ylabel('Humedad %')
plt.title('Demanda energetica de la zona 7')
plt.show()